# -*- coding: utf-8 -*-
"""app.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cvnBh_GhOaHWb4oArrRc4zhdqcPfVda2
"""

!pip install pyngrok -q
!pip install streamlit -q
!pip install wikipedia -q

# Commented out IPython magic to ensure Python compatibility.
# %%writefile app.py
# 
# import os
# import streamlit as st
# from typing import TypedDict, Annotated
# from langgraph.graph import StateGraph, START, END
# from langgraph.graph.message import add_messages
# from langgraph.checkpoint.memory import InMemorySaver
# from langchain_core.messages import BaseMessage, HumanMessage
# from langchain_core.tools import tool
# from langchain_groq import ChatGroq
# from langchain_community.tools import DuckDuckGoSearchRun
# from pydantic import BaseModel
# import pdfplumber
# 
# # -----------------------------
# # LLM SETUP
# # -----------------------------
# llm = ChatGroq(
#     model="llama-3.3-70b-versatile",
#     temperature=0,
#     api_key=os.environ.get("GROQ_API_KEY")
# )
# 
# class SearchEvaluation(BaseModel):
#     sufficient_results: bool
#     reason: str
# 
# evaluator_llm = llm.with_structured_output(SearchEvaluation)
# 
# # -----------------------------
# # TOOLS
# # -----------------------------
# search_tool = DuckDuckGoSearchRun()
# 
# from langchain_community.tools import WikipediaQueryRun
# from langchain_community.utilities import WikipediaAPIWrapper
# 
# wikipedia_tool = WikipediaQueryRun(
#     api_wrapper=WikipediaAPIWrapper(top_k_results=3)
# )
# tools = [search_tool, wikipedia_tool]
# llm_with_tools = llm.bind_tools(tools)
# 
# # -----------------------------
# # STATE
# # -----------------------------
# class LiteratureState(TypedDict):
#     messages: Annotated[list[BaseMessage], add_messages]
#     topic: str
#     search_results: list
#     summaries: list
#     gaps: list
#     search_attempts: int
#     sufficient_results: bool
#     final_report: str
# 
# # -----------------------------
# # NODES
# # -----------------------------
# def analyze_topic(state):
#     topic = state["messages"][-1].content
#     return {"topic": topic, "search_attempts": 0}
# 
# def search_papers_node(state):
#     topic = state["topic"]
# 
#     try:
#         web_results = search_tool.run(topic)
#     except Exception:
#         web_results = "Web search unavailable"
# 
#     try:
#         wiki_results = wikipedia_tool.run(topic)
#     except Exception:
#         wiki_results = "Wikipedia search unavailable"
# 
#     response = llm_with_tools.invoke(
#         f"Based on this topic: {topic}, "
#         f"what are the key search terms I should look for in literature?"
#     )
#     return {
#         "search_results": [web_results, wiki_results, response.content],
#         "search_attempts": state.get("search_attempts", 0) + 1
#     }
# 
# def evaluate_results(state):
#     results = str(state["search_results"])
#     evaluation = evaluator_llm.invoke(
#         f"""
#         Determine if enough literature exists
#         in the following search results.
#         Search Results: {results}
#         Return:
#         - sufficient_results = True if enough information exists
#         - sufficient_results = False if information is insufficient
#         """
#     )
#     return {"sufficient_results": evaluation.sufficient_results}
# 
# def route_results(state):
#     if state["sufficient_results"]:
#         return "summarize"
#     if state["search_attempts"] >= 2:
#         return "summarize"
#     return "refine_query"
# 
# def refine_query(state):
#     topic = state["topic"]
#     improved_query = f"latest research papers on {topic}"
#     return {"topic": improved_query}
# 
# def summarize_node(state):
#     results = str(state["search_results"])
#     response = llm.invoke(
#         f"""
#         Summarize the following literature search results.
#         Focus on key findings, main contributions, and important trends.
#         Search Results: {results}
#         """
#     )
#     return {"summaries": [response.content]}
# 
# def identify_gaps(state):
#     response = llm.invoke(
#         f"""
#         Based on the following literature summary:
#         {state['summaries']}
#         Identify:
#         - Research gaps
#         - Limitations
#         - Future opportunities
#         """
#     )
#     return {"gaps": [response.content]}
# 
# def final_report_node(state):
#     response = llm.invoke(
#         f"""
#         Create a literature review report.
#         Topic: {state['topic']}
#         Literature Summary: {state['summaries']}
#         Research Gaps: {state['gaps']}
#         Format:
#         1. Introduction
#         2. Key Findings
#         3. Research Questions
#         4. Research Gaps
#         5. Future Directions
#         6. Conclusion
#         """
#     )
#     return {"final_report": response.content}
# 
# # -----------------------------
# # GRAPH
# # -----------------------------
# graph = StateGraph(LiteratureState)
# graph.add_node("analyze_topic", analyze_topic)
# graph.add_node("search_papers", search_papers_node)
# graph.add_node("evaluate", evaluate_results)
# graph.add_node("refine_query", refine_query)
# graph.add_node("summarize", summarize_node)
# graph.add_node("identify_gaps", identify_gaps)
# graph.add_node("final_report", final_report_node)
# 
# graph.add_edge(START, "analyze_topic")
# graph.add_edge("analyze_topic", "search_papers")
# graph.add_edge("search_papers", "evaluate")
# graph.add_conditional_edges(
#     "evaluate", route_results,
#     {"summarize": "summarize", "refine_query": "refine_query"}
# )
# graph.add_edge("refine_query", "search_papers")
# graph.add_edge("summarize", "identify_gaps")
# graph.add_edge("identify_gaps", "final_report")
# graph.add_edge("final_report", END)
# 
# checkpointer = InMemorySaver()
# chatbot = graph.compile(checkpointer=checkpointer)
# 
# # -----------------------------
# # STREAMLIT UI
# # -----------------------------
# st.set_page_config(page_title="Literature Review Assistant", page_icon="📚")
# st.title("Literature Review Assistant")
# st.write("Enter a paper title or upload a PDF to generate a full literature review.")
# 
# tab1, tab2 = st.tabs(["Enter Paper Title", "Upload PDF"])
# 
# topic_input = None
# 
# with tab1:
#     paper_title = st.text_input("Paper Title or Topic", placeholder="e.g., Transformer models in NLP")
#     if paper_title:
#         topic_input = paper_title
# 
# with tab2:
#     uploaded_file = st.file_uploader("Upload PDF Paper", type="pdf")
#     if uploaded_file:
#         import pdfplumber
#         with pdfplumber.open(uploaded_file) as pdf:
#             text = ""
#             for page in pdf.pages[:3]:
#                 text += page.extract_text() or ""
#         topic_input = text[:500]
#         st.success("PDF uploaded! Extracted first 500 characters as topic.")
#         st.write(topic_input)
# 
# if st.button("Generate Literature Review") and topic_input:
#     with st.spinner("Searching and analyzing literature... this may take a minute ⏳"):
#         config = {"configurable": {"thread_id": "streamlit_user"}}
#         result = chatbot.invoke(
#             {"messages": [HumanMessage(content=topic_input)]},
#             config=config
#         )
# 
#     st.success("Done!")
# 
#     st.subheader("Final Report")
#     st.markdown(result["final_report"])
# 
#     with st.expander(" Summaries"):
#         for s in result["summaries"]:
#             st.write(s)
# 
#     with st.expander("Research Gaps"):
#         for g in result["gaps"]:
#             st.write(g)
# 
#     with st.expander(" Raw Search Results"):
#         st.write(result["search_results"])

!ngrok authtoken "3EqpndImRP3TOlDHvL8CgYHPgp5_83Cfvi5yaf7yzbvteQqMe"

!pip install langchain-groq langgraph langchain-community pdfplumber arxiv ddgs -q

import os
from pyngrok import ngrok

os.environ["GROQ_API_KEY"] = "GROQ_API_KEY"
public_url = ngrok.connect(8501)
print("App URL:", public_url)

!streamlit run app.py &